extern unsigned char TaskUtility_Public_Var_uChar1;
extern unsigned char TaskUtility_Public_Var_uChar2;
extern unsigned char TaskUtility_Public_Var_uChar3;
extern char TaskUtility_Public_Var_SegViewArr[16];